version: '3'
services:
    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - ./client:/app
        ports:
            - 3000:3000
        depends_on:
            - backend
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./server:/app
        ports:
            - 8000:8000
